sonar.issues.sandbox.enabled=true
sonar.issues.sandbox.default=true
sonar.issues.sandbox.override.enabled=true
sonar.issues.sandbox.software-qualities=[{"softwareQuality":"MAINTAINABILITY", "impactSeverities":["LOW","INFO"]}]

sonar.log.level=DEBUG

sonar.multi-quality-mode.enabled=false

sonar.search.host=0.0.0.0

sonar.secretKeyPath=conf/sonar-secret.txt

sonar.updatecenter.activate=false

sonar.web.accessLogs.pattern=%h %l %reqAttribute{LOGIN} [%t] '%r' %s %b '%i{Referer}' '%i{User-Agent}' '%reqAttribute{ID}'
sonar.web.systemPasscode={aes-gcm}MEMhXLqAn1S5xqtnvx+lF5qFxYbceinEGXoACgNezeAuEA==
