sonar.issues.sandbox.enabled=true
sonar.issues.sandbox.default=true
sonar.issues.sandbox.override.enabled=true
sonar.issues.sandbox.software-qualities=[{"softwareQuality":"MAINTAINABILITY", "impactSeverities":["LOW","INFO"]}]

sonar.log.level=DEBUG

sonar.multi-quality-mode.enabled=false

sonar.search.host=0.0.0.0

sonar.updatecenter.activate=false
